services:
  backend:
    build:
      context: ./qna_service
      dockerfile: ./Dockerfile
    command: python3 -m qna_service
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./qna_service/chroma_data:/code/chroma_data
    restart: always
